/*************************************************************************\
*
*                  Copyright (C) Michael Kerrisk, 2019.                   *
*                                                                         *
* This program is free software. You may use, modify, and redistribute it *
* under the terms of the GNU General Public License as published by the   *
* Free Software Foundation, either version 3 or (at your option) any      *
* later version. This program is distributed without any warranty.  See   *
* the file COPYING.gpl-v3 for details.                                    *
\*************************************************************************/

/* Listing 20-1 */

/* ouch.c

   Catch the SIGINT signal, generated by typing control-C (^C).

   Note that although we use signal() to establish the signal handler in this
   program, the use of sigaction() is always preferable for this task.

   Modified by Junji Tai 2025
*/

#include <signal.h>
#include <stdio.h>
#include <unistd.h>

#include "../lib/error_functions.h"

static void sigHandler(int sig)
{
    (void) sig;

    printf("Ouch!\n");   /* UNSAFE (see Section 21.1.2) */
}

int main(void)
{
    /* Establish handler for SIGINT. Here we use the simpler signal()
       API to establish a signal handler, but for the reasons described in
       Section 22.7 of TLPI, sigaction() is the (strongly) preferred API
       for this task. */

    if (signal(SIGINT, sigHandler) == SIG_ERR)
        errExit("signal");

    /* Loop continuously waiting for signals to be delivered */

    for (int j = 0; ; j++) {
        printf("%d\n", j);
        sleep(3);   /* Loop slowly... */
    }
}
